# SPDX-FileCopyrightText: 2023 DB Systel GmbH
#
# SPDX-License-Identifier: Apache-2.0

name: "Reusable Poetry build workflow"
inputs:
  python:
    default: "3.11"
    description: "Value for 'python-version'"
    required: false
    type: string
  poetry_args:
    default: ""
    description: "Additional arguments for the poetry install step'"
    required: false
    type: string
runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ inputs.python }}
    - name: Install dependencies
      run: |
        pip install poetry
        poetry install --no-interaction ${{ inputs.poetry_args }}
      shell: bash
