# SPDX-License-Identifier: CC0-1.0
# SPDX-FileCopyrightText: 2025 Max Mehl

name: Vulnerability Check of Latest Release/Tag

on:
  workflow_dispatch:  # allow to trigger manually
  schedule:
    - cron: "35 9 * * 1"  # run a check once a week

jobs:
  osv-check:
    runs-on: ubuntu-latest
    steps:
      - uses: mxmehl/latest-release-vulnerability-status@v1
